name: Main 🧠
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Generate example
        run: |
          cd example
          yarn install
          yarn build
          cd ..

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: example/dist

      - name: Push build to branch
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: "build/* -f"
