name: Main 🧠
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Generate example
        run: |
          cd example
          yarn install
          yarn build
          cd ..

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: example/dist

      - name: Get changes from changelog
        run: |
          chmod +x scripts/getChange.sh
          ./scripts/getChange.sh ${{steps.publish.outputs.version}} CHANGELOG.md > CHANGELOG.txt

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.txt
          files: build/*
          tag_name: ${{steps.publish.outputs.version}}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
